spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_app_db
    username: user
    password: bestuser

  jpa:
    show-sql: true
  jooq:
    sql-dialect: org.hibernate.dialect.MySQLDialect